repos:
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        language: system
        entry: make update-requirements
        always_run: true
        stages: [commit]
        pass_filenames: false
  - repo: local
    hooks:
    - id: black
      name: black
      entry: make lint
      language: system
      stages: [commit]
      types: [python]
      always_run: true
  - repo: local
    hooks:
    - id: isort
      name: isort
      entry: isort .
      language: system
      stages: [commit]
      types: [python]
      always_run: true
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: make lint-check
      language: system
      stages: [commit]
      types: [python]
      always_run: true
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: make test
        always_run: true
        pass_filenames: false
        stages: [commit]
